version: '3.8'

networks:
  MLOps2:
    name: MLOps_dev2
    driver: bridge 

services:
  vector-entropy-train:
    build:
      context: .
    container_name: vector-entropy-train
    volumes:
      - ./models:/app/models
    networks:
      - MLOps2

#-------------
# S3 MinIO (Упрощённый аналог AmazonS3) https://sanidhya235.medium.com/introduction-to-minio-193e8523a4a8
#-------------
  minio:
    image: quay.io/minio/minio:RELEASE.2022-02-18T01-50-10Z
    container_name: minio_s3_server
    networks:
      - MLOps2
    volumes:
      - ./volumes/minio/data:/data
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: 'minio_user'
      MINIO_ROOT_PASSWORD: 'minio_password'
      MINIO_ADDRESS: ':9000'
      MINIO_CONSOLE_ADDRESS: ':9001'
    command: minio server /data